In [ ]:
#import files
import os
import json
import pprint
import pandas as pd
import numpy as np
# import requests

In [66]:
df1 = pd.read_csv('state-population-table.csv')
df2 = pd.read_csv('state-population-table(1).csv')

df1 = df1.append(df2, ignore_index=True)

df1=df1.drop(columns=['rank','percent','growth','growthSince2010','pop2019','fips' ])
df1=df1[df1.state != 'Puerto Rico']

abbrevs={
    "AL": "Alabama",
    "AK": "Alaska",
    "AS": "American Samoa",
    "AZ": "Arizona",
    "AR": "Arkansas",
    "CA": "California",
    "CO": "Colorado",
    "CT": "Connecticut",
    "DE": "Delaware",
    "DC": "District of Columbia",
    "FM": "Federated States Of Micronesia",
    "FL": "Florida",
    "GA": "Georgia",
    "GU": "Guam",
    "HI": "Hawaii",
    "ID": "Idaho",
    "IL": "Illinois",
    "IN": "Indiana",
    "IA": "Iowa",
    "KS": "Kansas",
    "KY": "Kentucky",
    "LA": "Louisiana",
    "ME": "Maine",
    "MH": "Marshall Islands",
    "MD": "Maryland",
    "MA": "Massachusetts",
    "MI": "Michigan",
    "MN": "Minnesota",
    "MS": "Mississippi",
    "MO": "Missouri",
    "MT": "Montana",
    "NE": "Nebraska",
    "NV": "Nevada",
    "NH": "New Hampshire",
    "NJ": "New Jersey",
    "NM": "New Mexico",
    "NY": "New York",
    "NC": "North Carolina",
    "ND": "North Dakota",
    "MP": "Northern Mariana Islands",
    "OH": "Ohio",
    "OK": "Oklahoma",
    "OR": "Oregon",
    "PW": "Palau",
    "PA": "Pennsylvania",
    "PR": "Puerto Rico",
    "RI": "Rhode Island",
    "SC": "South Carolina",
    "SD": "South Dakota",
    "TN": "Tennessee",
    "TX": "Texas",
    "UT": "Utah",
    "VT": "Vermont",
    "VI": "Virgin Islands",
    "VA": "Virginia",
    "WA": "Washington",
    "WV": "West Virginia",
    "WI": "Wisconsin",
    "WY": "Wyoming"
}

abbrev_to_us_state = dict(map(reversed, abbrevs.items()))
df1.state.replace(abbrev_to_us_state, inplace=True)
df1=df1.drop(columns=['pop2023', 'pop2022', 'growthRate'])
df1.to_csv('filter_state.csv')

In [65]:
df1

                   state    densityMi   pop2020   pop2010    area
0                     CA    249.81347  39501653  37253956  155779
1                     TX    116.75553  29232474  25145561  261232
2                     FL    422.59351  21589602  18801310   53625
3                     NY    413.71663  20108296  19378102   47126
4                     PA    289.02749  12994440  12702379   44743
5                     IL    224.74459  12786580  12830632   55519
6                     OH    287.50579  11797517  11536504   40861
7                     GA    191.91701  10729828   9687653   57513
8                     NC    222.79940  10449445   9535483   48618
9                     MI    177.41244  10069577   9883640   56539
10                    NJ   1258.55820   9271689   8791894    7354
11                    VA    220.55895   8636471   8001024   39490
12                    WA    117.83476   7724031   6724540   66456
13                    AZ     65.61541   7179943   6392017  113594
14                    TN    173.01630   6925619   6346105   41235
15                    MA    894.13564   6995729   6547629    7800
16                    IN    191.27287   6788799   6483802   35826
17                    MO     89.98998   6153998   5988927   68742
18                    MD    634.04862   6173205   5773552    9707
19                    WI    109.03241   5896271   5686986   54158
20                    CO     56.62333   5784865   5029196  103642
21                    MN     71.87131   5709852   5303925   79627
22                    SC    178.70337   5131848   4625364   30061
23                    AL    100.67620   5031362   4779736   50645
24                    LA    105.39265   4651664   4533372   43204
25                    KY    114.42109   4507445   4339367   39486
26                    OR     44.00522   4244795   3831074   95988
27                    OK     59.01851   3964912   3751351   68595
28                    CT    749.49504   3597362   3574097    4842
29                    UT     41.65130   3283785   2763885   82170
30                    NV     29.23222   3115648   2700551  109781
31                    IA     57.34903   3190571   3046355   55857
32                    AR     58.86715   3014195   2915918   52035
33                    KS     35.91504   2937919   2853118   81759
34                    MS     62.45398   2958141   2967297   46923
35                    NM     17.39527   2118390   2059179  121298
36                    ID     23.88287   1849202   1567582   82643
37                    NE     25.67286   1962642   1826341   76824
38                    WV     73.41651   1791420   1852994   24038
39                    HI    223.14152   1451043   1360301    6423
40                    NH    156.70245   1378587   1316470    8953
41                    ME     45.17855   1363557   1328361   30843
42                    MT      7.82919   1087075    989415  145546
43                    RI   1054.62573   1096345   1052567    1034
44                    DE    529.49461    992114    897934    1949
45                    SD     12.18140    887799    814180   75811
46                    ND     11.31271    779518    672591   69001
47                    AK      1.28449    732923    710231  570641
48                    VT     70.21330    642893    625741    9217
49                    WY      6.00743    577605    563626   97093
51  District of Columbia  11062.54098    670868    601723      61